# fly.toml app configuration file generated for pedocs-backend on 2025-06-09T20:40:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pedocs-backend'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    type = "http"
    interval = "10s"
    timeout = "5s"
    grace_period = "20s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1